[build-system]
requires = ["setuptools>=80", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "chromy"
version = "1.0.0"
description = "Chromy is a minimal CLI RAG system based on Chromadb"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chromadb>=1.5.8",
    "openai>=2.32.0",
    "pymupdf4llm>=1.27.2.2",
    "python-dotenv>=1.2.2",
    "semchunk>=4.0.0",
    "tiktoken>=0.12.0",
    "transformers>=5.5.4",
]

[project.scripts]
chromy = "main:main"

[tool.setuptools]
packages = ["handlers"]
py-modules = [
    "main",
    "cli_app",
    "cli_parser",
    "chroma_functions",
    "chunk_functions",
    "embed",
    "utilities",
]

[dependency-groups]
dev = ["nuitka[onefile]>=4.0.8"]
