[project]
name = "chroma"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chromadb>=1.5.8",
    "openai>=2.32.0",
    "python-dotenv>=1.2.2",
    "semchunk>=4.0.0",
    "tiktoken>=0.12.0",
    "transformers>=5.5.4",
]

[dependency-groups]
dev = ["nuitka[onefile]>=4.0.8"]
