name: test

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Show basic info
        run: |
          echo "Hello from Gitea Actions"
          uname -a
